### ISSUE TITLE
Data needed in API?

### ISSUE THREAD

**Issue by Quantum-Codes** [Quantum-Codes/Profile-comments-API#6]
What data u need I api? Reply down.

1. Comment ID
2. Username of commenter and replier
3. Comment content

Anything else? 
And can anyone paste the HTML code of 1 comment with replies from  https://scratch.mit.edu/site-api/comments/user/Ankit_Anmol/ cuz I'm on tab

**Comment by Sid72020123** [comment]
I made all things now only comment ID is  remaining!

**Comment by Quantum-Codes** [comment]
That too done with timestamp
